services:
  # 1. El servicio del Backend (Node.js)
  backend:
    # Le decimos que construya usando el Dockerfile.backend
    build:
      context: .
      dockerfile: dockerFile.backend
    image: abransz/purolomo-backend:v1.3
    container_name: purolomo-backend
    # Mapeamos el puerto de la API
    ports:
      - "3001:3001"
    volumes:
      - ./historial.db:/app/historial.db
      - ./historial.sqbpro:/app/historial.sqbpro

  # 2. El servicio del Frontend
  frontend:
    # Le decimos que construya usando el Dockerfile.frontend
    build:
      context: .
      dockerfile: dockerfile.frontend
      args:
        VITE_API_URL: http://abrahan-server:3001/api
    image: abransz/purolomo-frontend:v1.3
    container_name: purolomo-frontend
    # Mapeamos el puerto de la App
    ports:
      - "3000:80"
    # Le decimos que debe esperar a que el 'backend' est√© listo
    depends_on:
      - backend
